# Generated by Django 5.1.5 on 2025-01-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-is_done", "created_at"]},
        ),
        migrations.RenameField(
            model_name="task",
            old_name="status",
            new_name="is_done",
        ),
        migrations.AlterField(
            model_name="task",
            name="content",
            field=models.CharField(max_length=255),
        ),
    ]
